// Generates the API types from the backend's OpenAPI schema. Never hand-write API types.
//   npm run gen:api     writes openapi.json and src/api/schema.d.ts
//   npm run check:api   fails if either file is out of date (run in CI)
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const root = fileURLToPath(new URL("..", import.meta.url));
const backend = fileURLToPath(new URL("../../backend", import.meta.url));
const schemaFile = `${root}openapi.json`;
const typesFile = `${root}src/api/schema.d.ts`;
const check = process.argv.includes("--check");

const schema = execFileSync("uv", ["run", "--quiet", "python", "scripts/dump_openapi.py"], {
  cwd: backend,
  encoding: "utf8",
}).replace(/\r\n/g, "\n");

const header = "// Generated by `npm run gen:api` from the backend's OpenAPI schema. Do not edit.\n\n";
const types = header + astToString(await openapiTS(JSON.parse(schema)));

const same = (file, text) =>
  existsSync(file) && readFileSync(file, "utf8").replace(/\r\n/g, "\n") === text;

if (check) {
  const stale = [[schemaFile, schema], [typesFile, types]].filter(([f, t]) => !same(f, t));
  if (stale.length) {
    console.error("Generated API types are out of date. Run `npm run gen:api` and commit.");
    process.exit(1);
  }
  console.log("API types are up to date.");
} else {
  writeFileSync(schemaFile, schema);
  writeFileSync(typesFile, types);
  console.log("Wrote openapi.json and src/api/schema.d.ts");
}
