"""The field registry: every question the intake can ask, with fixed, reviewed wording.

Wording here was reviewed by the product owner (docs/V2_SPEC.md §5.3). Do not rephrase
without review. The LLM never changes this text.
"""

from types import MappingProxyType

from app.domain.fields import NOT_SURE_ID, PREFER_NOT_ID, Condition, FieldDef, Option
from app.domain.types import InputType, IntakeType, NotSure, Tier

FI = IntakeType.FAMILY_INQUIRY
PR = IntakeType.PROVIDER_REFERRAL

NOT_SURE = Option(id=NOT_SURE_ID, label="I'm not sure", special="not_sure")
PREFER_NOT = Option(id=PREFER_NOT_ID, label="Prefer not to say", special="prefer_not")

IS_FI = Condition(field_id="intake_type", equals=FI)
IS_PR = Condition(field_id="intake_type", equals=PR)
RESPONDENT_NOT_PATIENT = Condition(field_id="relationship", not_equals="me")

INTAKE_TYPE_HELP = (
    "Choose the first one if you want care for yourself or someone you look after. "
    "Choose the second one if you are a health worker sending a patient to us."
)

FIELDS: tuple[FieldDef, ...] = (
    FieldDef(
        id="intake_type",
        section="start",
        order=1,
        tier=Tier.MUST_HAVE,
        input_type=InputType.CHOICE,
        question_self="Which one describes you?",
        question_other="Which one describes you?",
        single_wording=True,
        label_self="the kind of form",
        label_other="the kind of form",
        short_label="kind of form",
        why="We ask this so we only ask questions that fit you.",
        help=INTAKE_TYPE_HELP,
        options=(
            Option(id=FI, label="Care for me or someone I look after"),
            Option(id=PR, label="I am a health worker sending a referral"),
            NOT_SURE,
        ),
        not_sure=NotSure.CLARIFY,
    ),
    FieldDef(
        id="relationship",
        section="start",
        order=2,
        tier=Tier.MUST_HAVE,
        input_type=InputType.CHOICE,
        question_self="Who is this form for?",
        question_other="Who is this form for?",
        single_wording=True,
        label_self="who this form is for",
        label_other="who this form is for",
        short_label="who this form is for",
        why="We ask this so we can word the questions the right way.",
        help=(
            "Choose Me if this form is about you. "
            "If it is about someone else, choose how you know them."
        ),
        options=(
            Option(id="me", label="Me"),
            Option(id="child", label="My child"),
            Option(id="parent", label="My parent"),
            Option(id="partner", label="My partner"),
            Option(id="sibling", label="My brother or sister"),
            Option(id="look_after", label="Someone I look after"),
            Option(id="other_family", label="Another family member"),
            NOT_SURE,
        ),
        conditions=(IS_FI,),
        not_sure=NotSure.ANSWER,
    ),
    FieldDef(
        id="respondent_name",
        section="start",
        order=3,
        tier=Tier.MUST_HAVE,
        input_type=InputType.TEXT,
        question_self="What is your name?",
        question_other="What is your name?",
        single_wording=True,
        label_self="your name",
        label_other="your name",
        short_label="your name",
        why="We need to know who to talk to about this form.",
        help="Type your own name. This is the name of the person filling in this form.",
        example="Jordan Rivera",
        conditions=(IS_FI, RESPONDENT_NOT_PATIENT),
        about_respondent_in=frozenset({FI}),
    ),
    FieldDef(
        id="full_name",
        section="patient",
        order=4,
        tier=Tier.MUST_HAVE,
        input_type=InputType.TEXT,
        question_self="What is your full name?",
        question_other="What is the patient's full name?",
        label_self="your full name",
        label_other="the patient's full name",
        short_label="full name",
        why="We use this name to make a new record at the clinic.",
        help="Type the first name and the last name.",
        example="Alex Rivera",
    ),
    FieldDef(
        id="date_of_birth",
        section="patient",
        order=5,
        tier=Tier.REQUIRED,
        input_type=InputType.DATE,
        question_self="What is your date of birth?",
        question_other="What is the patient's date of birth?",
        label_self="your date of birth",
        label_other="the patient's date of birth",
        short_label="date of birth",
        why="We use the date of birth to find the right record.",
        help="Type the month, the day and the year.",
        example="May 4, 2004",
    ),
    FieldDef(
        id="preferred_contact_method",
        section="contact",
        order=6,
        tier=Tier.REQUIRED,
        input_type=InputType.CHOICE,
        question_self="How do you want us to contact you?",
        question_other="How do you want us to contact you?",
        single_wording=True,
        label_self="how you want us to contact you",
        label_other="how you want us to contact you",
        short_label="how to contact you",
        why="We will only contact you in the way you choose.",
        help="Choose how we should reach you when we have news about this form.",
        options=(
            Option(id="phone_call", label="Phone call"),
            Option(id="text_message", label="Text message"),
            Option(id="email", label="Email"),
            Option(id="letter", label="Letter in the mail"),
            NOT_SURE,
        ),
        conditions=(IS_FI,),
        about_respondent_in=frozenset({FI}),
        not_sure=NotSure.ANSWER,
    ),
    FieldDef(
        id="phone",
        section="contact",
        order=7,
        tier=Tier.CONDITIONAL,
        input_type=InputType.PHONE,
        question_self="What is your phone number?",
        question_other="What is the patient's phone number?",
        label_self="your phone number",
        label_other="the patient's phone number",
        short_label="phone number",
        why="We use this number only to talk about this form.",
        help="Type the phone number with the area code.",
        example="202-555-0100",
        about_respondent_in=frozenset({FI}),
    ),
    FieldDef(
        id="email",
        section="contact",
        order=8,
        tier=Tier.CONDITIONAL,
        input_type=InputType.EMAIL,
        question_self="What is your email address?",
        question_other="What is the patient's email address?",
        label_self="your email address",
        label_other="the patient's email address",
        short_label="email address",
        why="We use this email only to send messages about this form.",
        help="Type the email address. It has an @ sign in it.",
        example="alex@example.com",
        about_respondent_in=frozenset({FI}),
    ),
    FieldDef(
        id="address",
        section="contact",
        order=9,
        tier=Tier.CONDITIONAL,
        input_type=InputType.TEXT,
        question_self="What is your home address?",
        question_other="What is the patient's home address?",
        label_self="your home address",
        label_other="the patient's home address",
        short_label="home address",
        why="We use this address only to send letters about this form.",
        help="Type the street, the town, the state and the ZIP code.",
        example="12 Oak Street, Springfield, IL 62701",
        about_respondent_in=frozenset({FI}),
    ),
    FieldDef(
        id="inquiry_reason",
        section="reason",
        order=10,
        tier=Tier.REQUIRED,
        input_type=InputType.CHOICE,
        question_self="What do you want help with?",
        question_other="What does the patient need help with?",
        label_self="what you want help with",
        label_other="what the patient needs help with",
        short_label="help asked for",
        why="This helps us send your form to the right team.",
        help="A few words is enough.",
        options=(
            Option(id="autism_assessment", label="An autism assessment"),
            Option(id="therapy_support", label="Therapy or support"),
            Option(id="school_work", label="Help at school or work"),
            Option(id="something_else", label="Something else (type it)", free_text=True),
            NOT_SURE,
        ),
        conditions=(IS_FI,),
        not_sure=NotSure.ANSWER,
    ),
    FieldDef(
        id="referral_provider_name",
        section="referral",
        order=11,
        tier=Tier.REQUIRED,
        input_type=InputType.TEXT,
        question_self="What is the name of the provider who made this referral?",
        question_other="What is the name of the provider who made this referral?",
        single_wording=True,
        label_self="the name of the provider",
        label_other="the name of the provider",
        short_label="referring provider",
        why="We may need to talk to the provider about this referral.",
        help="Type the name of the doctor or other provider.",
        example="Dr. Sam Lee",
        conditions=(IS_PR,),
    ),
    FieldDef(
        id="referral_type",
        section="referral",
        order=12,
        tier=Tier.REQUIRED,
        input_type=InputType.CHOICE,
        question_self="What type of referral is this?",
        question_other="What type of referral is this?",
        single_wording=True,
        label_self="the type of referral",
        label_other="the type of referral",
        short_label="referral type",
        why="This helps us send the referral to the right team.",
        help="Choose the option that fits best.",
        options=(
            Option(id="physician", label="Physician"),
            Option(id="specialist", label="Specialist"),
            Option(id="emergency", label="Emergency"),
            NOT_SURE,
        ),
        conditions=(IS_PR,),
        not_sure=NotSure.ANSWER,
    ),
    FieldDef(
        id="referral_date",
        section="referral",
        order=13,
        tier=Tier.REQUIRED,
        input_type=InputType.DATE,
        question_self="What date was the referral made?",
        question_other="What date was the referral made?",
        single_wording=True,
        label_self="the referral date",
        label_other="the referral date",
        short_label="referral date",
        why="We use this date to keep track of the referral.",
        help="Type the month, the day and the year.",
        example="September 1, 2026",
        conditions=(IS_PR,),
    ),
    FieldDef(
        id="referral_mode",
        section="referral",
        order=14,
        tier=Tier.OPTIONAL,
        input_type=InputType.CHOICE,
        question_self="How was the referral sent?",
        question_other="How was the referral sent?",
        single_wording=True,
        label_self="how the referral was sent",
        label_other="how the referral was sent",
        short_label="how it was sent",
        why="This helps us find the first copy of the referral.",
        help="Choose how the referral reached us.",
        options=(
            Option(id="fax", label="Fax"),
            Option(id="phone", label="Phone"),
            Option(id="web_form", label="Web form"),
            NOT_SURE,
        ),
        conditions=(IS_PR,),
    ),
    FieldDef(
        id="preferred_name",
        section="patient",
        order=15,
        tier=Tier.OPTIONAL,
        input_type=InputType.TEXT,
        question_self="What name do you want us to use for you?",
        question_other="What name does the patient want us to use?",
        label_self="the name you want us to use",
        label_other="the name the patient wants us to use",
        short_label="name to use",
        why="We want to use the name that feels right.",
        help="This can be a short name or a different name. You can skip this.",
        example="Alex",
    ),
    FieldDef(
        id="gender",
        section="patient",
        order=16,
        tier=Tier.OPTIONAL,
        input_type=InputType.CHOICE,
        question_self="What is your gender?",
        question_other="What is the patient's gender?",
        label_self="your gender",
        label_other="the patient's gender",
        short_label="gender",
        why="This helps staff use the right words. You do not have to answer.",
        help="Choose the option that fits best. You can also type your own words.",
        options=(
            Option(id="woman", label="Woman"),
            Option(id="man", label="Man"),
            Option(id="non_binary", label="Non-binary"),
            Option(id="another", label="Another gender (type it)", free_text=True),
            PREFER_NOT,
            NOT_SURE,
        ),
    ),
)

BY_ID: MappingProxyType[str, FieldDef] = MappingProxyType({f.id: f for f in FIELDS})

SECTION_NAMES: MappingProxyType[str, tuple[str, str]] = MappingProxyType(
    {  # (self wording, other wording)
        "start": ("Getting started", "Getting started"),
        "patient": ("About you", "About the patient"),
        "contact": ("Contact details", "Contact details"),
        "reason": ("Reason for the form", "Reason for the form"),
        "referral": ("Referral details", "Referral details"),
    }
)


def get_field(field_id: str) -> FieldDef:
    return BY_ID[field_id]
