// Generated by `npm run gen:api` from the backend's OpenAPI schema. Do not edit.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/help/person": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Person Help
         * @description What to do to talk to a person when no form is open (e.g. after a lockout).
         */
        get: operations["person_help_help_person_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Intake */
        post: operations["create_intake_intakes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume With Code
         * @description Open an intake on a new device. Failures get one fixed answer, whether or not the
         *     code exists, and are rate-limited per code and per client.
         */
        post: operations["resume_with_code_intakes_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intake */
        get: operations["get_intake_intakes__intake_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/benefit-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Benefit Summary */
        post: operations["benefit_summary_intakes__intake_id__benefit_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Email
         * @description No recipient anywhere in this request: it is read from the stored email field.
         */
        post: operations["send_email_intakes__intake_id__email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_intakes__intake_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply */
        post: operations["reply_intakes__intake_id__replies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume
         * @description PAUSED -> where the user was. NEEDS_HUMAN -> "Continue on my own".
         */
        post: operations["resume_intakes__intake_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/resume-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Code
         * @description The resume code on request, any time after starting ("Take a break" area).
         */
        post: operations["resume_code_intakes__intake_id__resume_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review */
        get: operations["review_intakes__intake_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/review/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Edit */
        post: operations["review_edit_intakes__intake_id__review_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/staff-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff Summary */
        post: operations["staff_summary_intakes__intake_id__staff_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_intakes__intake_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/{intake_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_intakes__intake_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ui Text
         * @description Fixed interface wording, so the frontend writes none of its own.
         */
        get: operations["ui_text_ui_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionView */
        ActionView: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** BenefitLine */
        BenefitLine: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** BenefitSummary */
        BenefitSummary: {
            /**
             * Label Bottom
             * @default SYNTHETIC DEMO. These numbers are made up. They are not linked to any insurance plan.
             */
            label_bottom: string;
            /**
             * Label Top
             * @default SYNTHETIC DEMO. These numbers are made up. They are not linked to any insurance plan.
             */
            label_top: string;
            /** Lines */
            lines: components["schemas"]["BenefitLine"][];
            /** Member Name */
            member_name: string;
            /**
             * Source
             * @default field:full_name
             */
            source: string;
            /**
             * Title
             * @default Benefit summary (demo)
             */
            title: string;
        };
        /**
         * Choose
         * @description A button: an option id, "yes"/"no", "old"/"new"/"neither", or an ISO date choice.
         */
        Choose: {
            /** Extra Text */
            extra_text?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choose";
            /** Option Id */
            option_id: string;
        };
        /** EditRequest */
        EditRequest: {
            /** Field Id */
            field_id: string;
            /**
             * Turn
             * @description The turn number the client last saw.
             */
            turn: number;
        };
        /**
         * EmailRequest
         * @description Empty on purpose: there is no recipient. It comes from the stored email field.
         */
        EmailRequest: Record<string, never>;
        /**
         * ErrorBody
         * @description Every error: a fixed code and a fixed message. Never exception text or field values.
         */
        ErrorBody: {
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ActionView"][];
            /**
             * Code
             * @enum {string}
             */
            code: "invalid_request" | "intake_not_found" | "not_found" | "method_not_allowed" | "stale_turn" | "action_not_available" | "form_incomplete" | "idempotency_key_required" | "email_not_submitted" | "email_no_address" | "email_not_synthetic" | "email_failed" | "not_submitted" | "resume_failed" | "too_many_attempts" | "internal_error";
            /** Message */
            message: string;
            view?: components["schemas"]["TurnView"] | null;
        };
        /**
         * HelpView
         * @description Fixed text for "Talk to a person" when no form is open (e.g. locked out).
         */
        HelpView: {
            /** Info */
            info: string[];
        };
        /**
         * InputType
         * @enum {string}
         */
        InputType: "text" | "date" | "choice" | "phone" | "email";
        /** KeepGoing */
        KeepGoing: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "keep_going";
        };
        /** MarkUnknown */
        MarkUnknown: {
            /** Field Id */
            field_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mark_unknown";
        };
        /** OptionView */
        OptionView: {
            /**
             * Free Text
             * @default false
             */
            free_text: boolean;
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ProgressView */
        ProgressView: {
            /** About Total */
            about_total: number;
            /** Answered */
            answered: number;
            /** Exact */
            exact: boolean;
            /** Sections */
            sections: components["schemas"]["SectionView"][];
        };
        /** QuestionView */
        QuestionView: {
            /**
             * Autocomplete
             * @default off
             */
            autocomplete: string;
            /** Can Defer */
            can_defer: boolean;
            /** Can Skip */
            can_skip: boolean;
            /** Example */
            example: string | null;
            /** Field Id */
            field_id: string;
            input_type: components["schemas"]["InputType"];
            /** Kind */
            kind: string;
            /** Options */
            options: components["schemas"]["OptionView"][];
            /** Text */
            text: string;
            /** Why */
            why: string;
        };
        /** ReplyRequest */
        ReplyRequest: {
            /** Command */
            command: components["schemas"]["Choose"] | components["schemas"]["Text"] | components["schemas"]["Skip"] | components["schemas"]["Undo"] | components["schemas"]["KeepGoing"] | components["schemas"]["TalkToPerson"] | components["schemas"]["MarkUnknown"];
            /**
             * Turn
             * @description The turn number the client last saw.
             */
            turn: number;
        };
        /** ResumeCodeRequest */
        ResumeCodeRequest: {
            /** Resume Code */
            resume_code: string;
        };
        /**
         * ResumeCodeView
         * @description The resume code, on request from the "Take a break" area.
         */
        ResumeCodeView: {
            /** Info */
            info: string[];
            /** Resume Code */
            resume_code: string;
        };
        /** ReviewMissing */
        ReviewMissing: {
            /** Actions */
            actions: components["schemas"]["ActionView"][];
            /** Field Id */
            field_id: string;
            /** Label */
            label: string;
            /** Reason */
            reason: string | null;
            /** State */
            state: string;
        };
        /** ReviewRow */
        ReviewRow: {
            /** Display */
            display: string;
            /** Field Id */
            field_id: string;
            /** Label */
            label: string;
            /** Section */
            section: string;
        };
        /** ReviewView */
        ReviewView: {
            /** Answered */
            answered: components["schemas"]["ReviewRow"][];
            /** Can Submit */
            can_submit: boolean;
            /** Missing */
            missing: components["schemas"]["ReviewMissing"][];
        };
        /** SectionView */
        SectionView: {
            /** Done */
            done: boolean;
            /** Name */
            name: string;
        };
        /**
         * SessionView
         * @description A new intake, or one opened on a new device with a resume code.
         */
        SessionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Token */
            token: string;
            view: components["schemas"]["TurnView"];
        };
        /**
         * Skip
         * @description "Skip" on optional fields, "Answer later" on needed ones.
         */
        Skip: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "skip";
        };
        /** StaffSummary */
        StaffSummary: {
            /**
             * Disclaimer
             * @default Draft for staff review. Built from the form answers only. Not a clinical document.
             */
            disclaimer: string;
            /** Not Answered */
            not_answered: components["schemas"]["Statement"][];
            /** Notes */
            notes: components["schemas"]["Statement"][];
            /** Sections */
            sections: {
                [key: string]: components["schemas"]["Statement"][];
            };
            /**
             * Title
             * @default Intake summary for staff
             * @constant
             */
            title: "Intake summary for staff";
        };
        /**
         * State
         * @enum {string}
         */
        State: "greeting" | "choose_intake_type" | "collecting" | "confirming_extra" | "resolving_conflict" | "review" | "submitted" | "paused" | "needs_human";
        /** Statement */
        Statement: {
            /** Sources */
            sources: string[];
            /** Text */
            text: string;
        };
        /** TalkToPerson */
        TalkToPerson: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "talk_to_person";
        };
        /** Text */
        Text: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Text */
            text: string;
        };
        /** TurnRequest */
        TurnRequest: {
            /**
             * Turn
             * @description The turn number the client last saw.
             */
            turn: number;
        };
        /** TurnView */
        TurnView: {
            /** Acknowledgement */
            acknowledgement: string | null;
            /** Actions */
            actions: components["schemas"]["ActionView"][];
            /** Info */
            info: string[];
            progress: components["schemas"]["ProgressView"];
            question: components["schemas"]["QuestionView"] | null;
            /** Resume Code */
            resume_code?: string | null;
            review: components["schemas"]["ReviewView"] | null;
            state: components["schemas"]["State"];
            /** Turn */
            turn: number;
        };
        /**
         * UiText
         * @description Every fixed word the frontend shows besides questions and answers (principle P3).
         */
        UiText: {
            /** Buttons */
            buttons: {
                [key: string]: string;
            };
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Sentences */
            sentences: {
                [key: string]: string;
            };
        };
        /** Undo */
        Undo: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "undo";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    person_help_help_person_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpView"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_intake_intakes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    resume_with_code_intakes_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_intake_intakes__intake_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    benefit_summary_intakes__intake_id__benefit_summary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenefitSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    send_email_intakes__intake_id__email_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EmailRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    pause_intakes__intake_id__pause_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reply_intakes__intake_id__replies_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    resume_intakes__intake_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    resume_code_intakes__intake_id__resume_code_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCodeView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    review_intakes__intake_id__review_get: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    review_edit_intakes__intake_id__review_edit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    staff_summary_intakes__intake_id__staff_summary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_intakes__intake_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    submit_intakes__intake_id__submit_post: {
        parameters: {
            query?: never;
            header?: {
                "x-intake-token"?: string | null;
            };
            path: {
                intake_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    ui_text_ui_text_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiText"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
